name: "Deploy AWS Lambda "

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: # lambda function name
# also need secrets.AWS_ACCESS_KEY_ID, secrets.AWS_SECRET_ACCESS_KEY

on: # trigger for pipeline
  push: # for dev, auto deploy on push
    branches:
      - dev
  # or
  workflow_dispatch: # for production, no automated deploys

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Set GIT_SHA"
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Verify AWS authentication"
        run: aws sts get-caller-identity

      - name: "Create deployment package"
        run: |
          zip -r function.zip . -x "*.github/*" 

      - name: "Deploy to Lambda"
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip