FROM --platform=linux/amd64 node:20.11.1


RUN apt-get update  && \
    apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev
WORKDIR app

COPY . .
RUN npm install

CMD ["npm", "run", "dev"]