FROM python:3.13

WORKDIR /

RUN apt-get update

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 8000

COPY . .

CMD [ "gunicorn", "main:app", "-b", "0.0.0.0:8000", "--workers", "1", "--log-level", "debug"]