FROM python:3.11-slim

RUN apt-get update
RUN apt-get install poppler-utils -y
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
COPY ./ /app

CMD ["uvicorn", "application:application", "--host", "0.0.0.0", "--port", "80"]